[application]
name = "reverie-ui"
default_platform = "web"

[web.app]
title = "Reverie Music Server"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
dev_server_port = 8080
style = ["assets/tailwind.css"]

[web.resource.dev]

# Same as [web.resource], but for development servers
style = ["assets/tailwind.css"]
script = []

[[web.proxy]]
backend = "http://localhost:4533/rest"
